name: generate themes on push
run-name: generate themes (triggered by ${{ github.actor }})

on: 
  push:
    branches: [main]
    
jobs:
  gen-themes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v4
        - name: "Generate CSS files"
          run: python ./generate.py
        - name: "Configure git username"
          run: git config --local user.name actions-user
        - name: "Configure git email"
          run: git config --local user.email "actions@github.com"
        - name: "Check for changes"
          run: git status
        - name: "Stage changed files"
          run: git add .
        - name: "Check for changes"
          run: |
            if [-z "$(git status --porcelain)" ]; then
              echo "No changes, success"
              exit 0
        - name: "Commit changed files"
          run: git commit -m "Autogenerating CSS"
        - name: "Push changes"
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true